name: Receive Prefect Webhook
on:
  repository_dispatch:
    types: [prefect_webhook]
jobs:
  receive:
    runs-on: ubuntu-latest
    steps:
      - id: 'receive-prefect-webhook'
        run: |
          echo ${{ toJson(github.event.client_payload) }}
