name: repository-dispatch

on:
  repository_dispatch:
    types: [register-flow]

jobs:
  check-request:
    runs-on: ubuntu-latest
    steps:
      - id: 'check-request'
        run: |
          echo ${{ github.event }}
 
