name: run-command-slash-dispatch

on:
  repository_dispatch:
    types: [run-command]
    
env:
  PAYLOAD_CONTEXT: ${{ toJson(github.event.client_payload) }}

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - id: 'run-container'
        name: 'Pass PAYLOAD_CONTEXT to Dockerized click application to parse and run'
        run: |
          docker run -i \
          pangeo/pangeo-forge-registrar-images:latest \
          parse \
          "${{ env.PAYLOAD_CONTEXT }}" \
