# Compare: https://github.com/pangeo-forge/pangeo-forge-recipes/blob/master/.github/workflows/main.yaml

name: term width

on: workflow_dispatch

env:
  PYTEST_ADDOPTS: "--color=yes"

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Run Tests
        shell: bash -l {0}
        run: |
          python3 -c "import os; terminal_width = os.get_terminal_size().columns; print(terminal_width)"

